import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderBestiary } from './uopve-bestiary.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const base = '/uopve/';
const articleUrl = article => `${base}wiki/${article.slug}/`;
const dateLabel = date => new Date(`${date}T00:00:00Z`).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
const validDate = date => /^\d{4}-\d{2}-\d{2}$/.test(date) && Number.isFinite(Date.parse(date)) && new Date(date).toISOString().slice(0, 10) === date;
const validChangedAt = update => !update.changedAt || (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2})$/.test(update.changedAt) && Number.isFinite(Date.parse(update.changedAt)) && new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/London' }).format(new Date(update.changedAt)) === update.date);
const updateDateLabel = update => update.changedAt ? new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Europe/London', timeZoneName: 'short' }).format(new Date(update.changedAt)) : dateLabel(update.date);
const navItems = [['overview', 'The realm', base], ['introduction', 'Introduction', `${base}introduction/`], ['wiki', 'Wiki', `${base}wiki/`], ['downloads', 'Downloads', `${base}downloads/`], ['updates', 'Updates', `${base}updates/`]];
const paragraphs = values => (values || []).map(value => `<p>${esc(value)}</p>`).join('\n');
const tableContent = (table, section, index) => {
  const prefix = `reference-${section.id}-${index}`;
  const filter = table.rows.length > 15;
  return `${filter ? `<div class="reference-tools"><label for="${prefix}-search">Find in ${esc(table.caption || section.title)}<input id="${prefix}-search" type="search" maxlength="150" placeholder="Filter by name or value…" data-reference-filter="${prefix}"></label><p id="${prefix}-results" role="status" aria-live="polite">${table.rows.length} entries</p></div>` : ''}<div class="reference-table" tabindex="0" role="region" aria-label="${esc(table.caption || section.title)}"><table>${table.caption ? `<caption>${esc(table.caption)}</caption>` : ''}<thead><tr>${table.columns.map(column => `<th scope="col">${esc(column)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row => `<tr${filter ? ` data-reference-entry="${prefix}" data-search="${esc(row.join(' '))}"` : ''}>${row.map((cell, cellIndex) => cellIndex === 0 ? `<th scope="row">${esc(cell)}</th>` : `<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${filter ? `<p id="${prefix}-empty" class="callout" hidden>No entries match. Clear the search to see the full table.</p>` : ''}`;
};
const articleSearch = article => [article.title, article.category, article.summary, article.keywords, ...article.sections.flatMap(section => [section.title, ...(section.paragraphs || []), ...(section.lists || []).flatMap(list => list.items), ...(section.tables || []).flatMap(table => table.rows.flat())])].join(' ');
const sectionContent = section => paragraphs(section.paragraphs)
  + (section.lists || []).map(list => `${list.title ? `<h3>${esc(list.title)}</h3>` : ''}<ul>${list.items.map(item => `<li>${esc(item)}</li>`).join('')}</ul>`).join('\n')
  + (section.tables || []).map((table, index) => tableContent(table, section, index)).join('\n');
const button = (url, text, secondary = false) => `<a class="button${secondary ? ' button-secondary' : ''}" href="${esc(url)}">${esc(text)}</a>`;
const breadcrumb = (label, article = false) => `<nav class="breadcrumb wrap" aria-label="Breadcrumb"><a href="/">UO Workshop</a><span aria-hidden="true">/</span><a href="${base}">UO:PvE</a>${article ? `<span aria-hidden="true">/</span><a href="${base}wiki/">Wiki</a>` : ''}<span aria-hidden="true">/</span><span aria-current="page">${esc(label)}</span></nav>`;

function page({ title, description, path, active, content }) {
  const url = `https://www.uoassets.com${path}`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} · UO:PvE</title><meta name="description" content="${esc(description)}">
<link rel="canonical" href="${url}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} · UO:PvE"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="https://www.uoassets.com/uopve/media/realm.png">
<link rel="stylesheet" href="/uopve/uopve.css"><script src="/uopve/uopve.js" defer></script></head>
<body class="pve"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="header-inner"><a class="brand" href="/uopve/" aria-label="UO:PvE home"><span class="brand-mark" aria-hidden="true">UO</span><span class="brand-copy">UO:PvE<small>Adventure awaits in Britannia</small></span></a><nav class="global-nav" aria-label="UO Workshop"><a href="/">Asset library</a><a href="/studio/">UO Asset Studio</a><a href="/client/">Custom ClassicUO</a></nav></div></header>
<nav class="section-nav" aria-label="UO:PvE"><div class="wrap">${navItems.map(([id, label, href]) => `<a href="${href}"${id === active ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</div></nav>
<main id="main">${content}</main>
<footer class="site-footer"><div class="footer-inner wrap"><div><a class="brand" href="/uopve/">UO:PvE</a><p>A new adventure in a familiar world.</p></div><nav aria-label="Footer"><a href="/uopve/wiki/">Player wiki</a><a href="/uopve/downloads/">Downloads</a><a href="/uopve/updates/">Updates</a><a href="/">UO Workshop</a></nav></div></footer>
</body></html>
`;
}

export async function buildUopve() {
  const data = JSON.parse(await readFile(resolve(root, 'data/uopve.json'), 'utf8'));
  const { release, articles, updates } = data;
  const launcherVersion = release.launcherVersion || release.version;
  if (!/^\d+\.\d+\.\d+$/.test(launcherVersion)) throw Error('UO:PvE launcher version is invalid.');
  const bestiary = articles.some(article => article.catalog === 'bestiary') ? JSON.parse(await readFile(resolve(root, 'data/uopve-bestiary.json'), 'utf8')) : null;
  const bestiaryHtml = bestiary ? renderBestiary(bestiary) : '';
  const slugs = new Set(articles.map(article => article.slug));
  if (!articles.length || slugs.size !== articles.length || articles.some(article => !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(article.slug))) throw Error('UO:PvE wiki needs unique safe article slugs.');
  if (!validDate(release.date) || !/^\d+\.\d+\.\d+$/.test(release.version) || release.tag !== `client-v${release.version}` || !/^[a-f0-9]{64}$/.test(release.sha256) || !Number.isSafeInteger(release.sizeBytes) || release.sizeBytes < 1) throw Error('UO:PvE release metadata is invalid.');
  const releasePrefix = `https://github.com/Celobra/UOPvE-Client/releases/download/${release.tag}/`;
  if (release.installer !== `${releasePrefix}UOPvE-Setup.exe` || release.portable !== `${releasePrefix}UOPvE-Launcher.exe` || release.url !== `https://github.com/Celobra/UOPvE-Client/releases/tag/${release.tag}`) throw Error('UO:PvE downloads must match the named public release.');
  for (const article of articles) {
    const ids = article.sections.map(section => section.id);
    if (new Set(ids).size !== ids.length || ids.some(id => !/^[a-z0-9-]+$/.test(id)) || ids.some(id => ['main', 'article-title', 'related-title'].includes(id))) throw Error(`Invalid section anchors in ${article.slug}.`);
    if ((article.related || []).some(slug => !slugs.has(slug))) throw Error(`Unknown related article in ${article.slug}.`);
    if (article.catalog && article.catalog !== 'bestiary') throw Error(`Unknown catalogue in ${article.slug}.`);
    if (article.catalog === 'bestiary' && ids.some(id => ['creature-catalogue', 'loot-selections'].includes(id))) throw Error(`Reserved catalogue anchor in ${article.slug}.`);
    for (const section of article.sections) {
      for (const table of section.tables || []) {
        if (!Array.isArray(table.columns) || !table.columns.length || !Array.isArray(table.rows) || table.rows.some(row => !Array.isArray(row) || row.length !== table.columns.length || row.some(cell => typeof cell !== 'string'))) throw Error(`Invalid reference table in ${article.slug}/${section.id}.`);
      }
      if ((section.lists || []).some(list => !Array.isArray(list.items) || list.items.some(item => typeof item !== 'string'))) throw Error(`Invalid reference list in ${article.slug}/${section.id}.`);
    }
  }
  if (new Set(updates.map(update => update.id)).size !== updates.length || updates.some(update => !validDate(update.date) || !validChangedAt(update) || ['main', 'update-search', 'update-results', 'update-empty'].includes(update.id) || !/^[a-z0-9-]+$/.test(update.id) || !(/^\/uopve\//.test(update.link) || update.link.startsWith('https://github.com/Celobra/UOPvE-Client/releases/')))) throw Error('UO:PvE updates need unique IDs, publication dates and valid links.');

  async function save(path, options) {
    const directory = resolve(root, 'public', path.replace(/^\//, ''));
    await mkdir(directory, { recursive: true });
    await writeFile(resolve(directory, 'index.html'), page({ ...options, path }), 'utf8');
  }
  const latest = updates[0];
  await save(base, {
    title: 'Adventure awaits in Britannia', description: 'Discover UO:PvE: quests, character progression and the Hunter’s Guild. Find the player wiki, Windows client downloads and latest updates.', active: 'overview',
    content: `<section class="hero-grid wrap"><div class="hero-copy"><p class="eyebrow">ULTIMA ONLINE · A WORLD TO EXPLORE</p><h1>Your next<br><em>adventure awaits.</em></h1><p class="lead">Welcome to UO:PvE. Follow a quest, develop your character and take on the wilds of Britannia with the Hunter’s Guild at your side.</p><div class="actions">${button('/uopve/downloads/', 'Download & play ↓')}${button('/uopve/introduction/', 'Discover the realm →', true)}</div><p class="hero-meta">Windows client · ClassicUO · Optional Razor<br>Launcher ${esc(launcherVersion)} · Client release ${esc(release.version)}<br>Game files update automatically</p></div><figure class="hero-visual"><img src="/uopve/media/realm.png" width="640" height="480" alt="UO:PvE realm artwork: moonlit castles overlooking a mountain lake"><figcaption>Adventure awaits in Britannia · UO:PvE launcher artwork</figcaption></figure></section>
<section class="section wrap" aria-labelledby="hub-title"><div class="section-heading"><p class="eyebrow">YOUR JOURNEY STARTS HERE</p><h2 id="hub-title">Find your way into the realm.</h2><p>Everything you need to get ready, learn the world and keep up with what’s new.</p></div><div class="portal-grid">${[
      ['01', 'Introduction', 'Meet UO:PvE and discover the quests, hunts and progression that shape your adventure.', 'introduction', 'Explore the realm'],
      ['02', 'Player wiki', 'From your first quest to your next talent point. Search the guides and find your footing.', 'wiki', 'Open the wiki'],
      ['03', 'Downloads', 'Get the Windows installer, set up ClassicUO and let the launcher keep your game current.', 'downloads', 'Get ready to play'],
      ['04', 'Updates', 'Read dated gameplay changes, client releases and new player guides.', 'updates', 'Read the latest']
    ].map(([n, title, text, route, action]) => `<article class="portal-card"><span class="card-number" aria-hidden="true">${n}</span><h3>${title}</h3><p>${text}</p><a class="text-link" href="/uopve/${route}/">${action} →</a></article>`).join('')}</div></section>
<section class="section wrap split"><div><p class="eyebrow">QUESTS. COMPANIONS. PROGRESSION.</p><h2>An adventure<br>that grows with you.</h2><p>Accept a Guild contract, follow The Undying March or develop a companion through combat. Classes, talents and earned titles give you more to work towards.</p><a class="text-link" href="/uopve/wiki/getting-started/">Read your first steps →</a></div><aside class="panel"><p class="eyebrow">LATEST UPDATE</p><span class="tag">${esc(latest.category)}</span><p><time datetime="${latest.date}">${dateLabel(latest.date)}</time></p><h3>${esc(latest.title)}</h3><p>${esc(latest.summary)}</p><a class="text-link" href="/uopve/updates/#${latest.id}">Read the update →</a></aside></section>`
  });

  await save(`${base}introduction/`, {
    title: 'Welcome to the realm', description: 'An introduction to UO:PvE, its quests, Hunter’s Guild, classes, talents and companion progression.', active: 'introduction',
    content: `${breadcrumb('Introduction')}<section class="page-heading wrap"><p class="eyebrow">WELCOME TO UO:PvE</p><h1>A familiar world.<br><em>A fresh adventure.</em></h1><p class="lead">UO:PvE brings quests, character progression and the Hunter’s Guild to Ultima Online. Set out into Britannia with a new goal, an old friend or a companion of your own.</p></section>
<section class="section wrap feature-grid"><article class="feature-card"><span class="card-number">01 / ADVENTURE</span><h2>Follow the next quest.</h2><p>Take on supply deliveries, monster bounties and expeditions. Follow the seven stages of The Undying March, with your journal keeping track along the way.</p><a class="text-link" href="/uopve/wiki/quest-journal/">Quests & the journal →</a></article><article class="feature-card"><span class="card-number">02 / THE GUILD</span><h2>Answer the call.</h2><p>Visit the Hunter’s Guildmaster in Britain. Accept contracts, join the weekly quarry hunt, earn Guild Marks and work towards the Guild’s rewards.</p><a class="text-link" href="/uopve/wiki/hunters-guild/">Meet the Hunter’s Guild →</a></article><article class="feature-card"><span class="card-number">03 / YOUR CHARACTER</span><h2>Make progress your own.</h2><p>Choose from nine classes, develop talents as you level and collect achievement titles. Your pets can gain experience and grow through combat, too.</p><a class="text-link" href="/uopve/wiki/classes-and-talents/">Classes & talents →</a></article></section>
<section class="section wrap split"><div><p class="eyebrow">ONE LAUNCHER. YOUR NEXT JOURNEY.</p><h2>Get ready for Britannia.</h2><p>The Windows installer opens the UO:PvE launcher, which downloads ClassicUO and the game files. It checks for updated files and maps whenever you open it and before you play.</p><p>Razor is optional. Choose ClassicUO on its own or enable the included plugin in the launcher.</p><div class="actions">${button('/uopve/downloads/', 'Download for Windows ↓')}${button('/uopve/wiki/getting-started/', 'Read the starting guide →', true)}</div></div><figure class="hero-visual"><img src="/uopve/media/launcher.png" width="1180" height="750" loading="lazy" alt="UO:PvE 1.0.1 Windows launcher with install, import, verify and PLAY controls"><figcaption>The UO:PvE Windows launcher · interface shown in version 1.0.1</figcaption></figure></section>`
  });

  const categories = [...new Set(articles.map(article => article.category))];
  const guideNavigation = current => categories.map(category => `<details class="guide-topic"${category === current.category ? ' open' : ''}><summary>${esc(category)}</summary>${articles.filter(article => article.category === category).map(article => `<a href="${articleUrl(article)}"${article.slug === current.slug ? ' aria-current="page"' : ''}>${esc(article.title)}</a>`).join('')}</details>`).join('');
  await save(`${base}wiki/`, {
    title: 'Player wiki', description: 'Search UO:PvE spell damage, weapon swing times, creatures, treasure maps, classes, crafting, quests and housing.', active: 'wiki',
    content: `${breadcrumb('Wiki')}<section class="page-heading wrap"><p class="eyebrow">THE PLAYER WIKI</p><h1>A little knowledge.<br><em>A better adventure.</em></h1><p class="lead">Look up spell damage and swing times, compare creatures, plan a treasure hunt and find recipes, quests and rewards.</p></section><section class="section wrap"><div class="wiki-tools" role="search" aria-label="Search the wiki"><label for="wiki-search">Search the guides<input id="wiki-search" type="search" maxlength="150" placeholder="Try spell damage, treasure maps, dragon or crafting…"></label><label for="wiki-category">Browse a topic<select id="wiki-category"><option value="all">All topics</option>${categories.map(category => `<option value="${esc(category)}">${esc(category)}</option>`).join('')}</select></label></div><p id="wiki-results" role="status" aria-live="polite">${articles.length} guides</p><div class="wiki-grid">${articles.map(article => `<article class="wiki-card" data-wiki-entry data-category="${esc(article.category)}" data-search="${esc(articleSearch(article))}"><span class="tag">${esc(article.category)}</span><h2><a href="${articleUrl(article)}">${esc(article.title)}</a></h2><p>${esc(article.summary)}</p><a class="text-link" href="${articleUrl(article)}" aria-label="Read ${esc(article.title)}">Read the guide →</a></article>`).join('')}</div><p id="wiki-empty" class="callout" hidden>No guides match that search. Try a shorter term or choose All topics.</p><noscript><p class="callout">All guides are listed here. Enable JavaScript to filter by topic or search.</p></noscript><p class="callout">These guides describe the current UO:PvE configuration. Check the in-game panels for current requirements and rewards as the server develops.</p></section>`
  });
  for (const article of articles) {
    await save(articleUrl(article), {
      title: article.title, description: article.summary, active: 'wiki',
      content: `${breadcrumb(article.title, true)}<div class="article-layout wrap"><aside class="wiki-sidebar"><p class="eyebrow">PLAYER GUIDES</p><nav aria-label="Wiki articles">${guideNavigation(article)}</nav><p class="eyebrow">ON THIS PAGE</p><nav aria-label="On this page">${article.sections.map(section => `<a href="#${section.id}">${esc(section.title)}</a>`).join('')}${article.catalog === 'bestiary' ? '<a href="#creature-catalogue">Creature catalogue</a><a href="#loot-selections">Loot selections</a>' : ''}</nav></aside><article class="article-body"><header class="page-heading"><p class="eyebrow">${esc(article.category)}</p><h1 id="article-title">${esc(article.title)}</h1><p class="lead">${esc(article.summary)}</p></header>${article.sections.map(section => `<section id="${section.id}"><h2>${esc(section.title)}</h2>${sectionContent(section)}</section>`).join('')}${article.catalog === 'bestiary' ? bestiaryHtml : ''}<aside class="callout">Guidance follows the current UO:PvE configuration. Use the in-game panels for the latest requirements and rewards.</aside><section aria-labelledby="related-title"><h2 id="related-title">Continue your adventure</h2><ul>${(article.related || []).map(slug => { const related = articles.find(other => other.slug === slug); return `<li><a href="${articleUrl(related)}">${esc(related.title)}</a></li>`; }).join('')}</ul><a class="text-link" href="/uopve/wiki/">← All player guides</a></section></article></div>`
    });
  }

  await save(`${base}downloads/`, {
    title: 'Downloads & installation', description: 'Download the UO:PvE Windows installer or portable launcher. Set up ClassicUO, update your game files and connect to the shard.', active: 'downloads',
    content: `${breadcrumb('Downloads')}<section class="page-heading wrap"><p class="eyebrow">WINDOWS DOWNLOADS / ${esc(release.version)}</p><h1>Your adventure<br><em>starts here.</em></h1><p class="lead">Install the UO:PvE launcher. It takes care of ClassicUO, the game files and future map updates.</p></section><section class="section wrap"><article class="download-card"><span class="download-icon" aria-hidden="true">↓</span><div class="download-content"><span class="tag">RECOMMENDED / WINDOWS</span><h2>UO:PvE installer</h2><p>Installs the launcher for your Windows user and creates shortcuts. Setup opens the launcher to download the game.</p><p>Launcher ${esc(launcherVersion)} · Client release ${esc(release.version)}<br>${Math.round(release.sizeBytes / 1024)} KiB installer · ${dateLabel(release.date)}<br>Initial game download: about 2.2 GB · ClassicUO + optional Razor</p><div class="actions">${button(release.installer, 'Download UOPvE-Setup.exe ↓')}${button(release.url, 'Release notes ↗', true)}</div></div></article><div class="split section"><article class="panel"><p class="eyebrow">PORTABLE OPTION</p><h2>Already know your way?</h2><p>Download the standalone launcher if you prefer to run it from a folder. It uses the same update service and can install or import the game files.</p><a class="text-link" href="${esc(release.portable)}">Download UOPvE-Launcher.exe ↓</a></article><aside class="panel"><p class="eyebrow">BEFORE YOU BEGIN</p><dl class="facts-grid"><div><dt>Platform</dt><dd>Windows 64-bit</dd></div><div><dt>Runtime</dt><dd>.NET Framework 4.8</dd></div><div><dt>Game files</dt><dd>About 2.2 GB, plus update space</dd></div><div><dt>Client data</dt><dd>${esc(release.clientVersion)}</dd></div></dl><p>The small installer downloads the game through the launcher. Keep the launcher open until the download finishes.</p></aside></div></section>
<section class="section wrap" aria-labelledby="installation-title"><div class="section-heading"><p class="eyebrow">FROM DOWNLOAD TO PLAY</p><h2 id="installation-title">Three steps into the realm.</h2></div><ol class="step-list"><li><span class="step-number" aria-hidden="true">01</span><div class="step-content"><h3>Install the launcher</h3><p>Open UOPvE-Setup.exe and choose Install UO:PvE. Setup installs for your current Windows user and opens the launcher.</p></div></li><li><span class="step-number" aria-hidden="true">02</span><div class="step-content"><h3>Let your world download</h3><p>Keep the launcher open while it downloads ClassicUO and the game files. Check the game folder in Settings. Leave Launch with Razor unchecked unless you want to use the included plugin.</p></div></li><li><span class="step-number" aria-hidden="true">03</span><div class="step-content"><h3>Choose PLAY</h3><p>Once installation completes, choose PLAY and enter your account details in ClassicUO. The default connection is ${esc(release.serverHost)}:${release.serverPort}.</p></div></li></ol><div class="callout"><strong>Already have a compatible client?</strong><p>Use Import files and select the folder containing your game data and ClassicUO. Import into a new or empty game folder.</p></div></section>
<section class="section wrap split"><div><p class="eyebrow">READY FOR THE NEXT UPDATE</p><h2>Keep your world current.</h2><p>Client release ${esc(release.version)} makes character names and city descriptions readable. If you already use launcher ${esc(launcherVersion)}, close ClassicUO and reopen the launcher to download the small client update automatically.</p><p>To upgrade an earlier launcher, download and run the current UOPvE-Setup.exe once. The launcher checks for new game files and maps when it opens and before PLAY. Close ClassicUO before applying an update. Verify / repair can restore missing or changed release files.</p><a class="text-link" href="/uopve/wiki/launcher-and-updates/">Read the launcher & repair guide →</a><details><summary>Installer and portable launcher checksum</summary><p>SHA-256 for both files in release ${esc(release.version)}:</p><code>${release.sha256}</code><p>Both executables use the same build; the Setup filename opens installation mode.</p></details></div><figure class="hero-visual"><img src="/uopve/media/launcher.png" width="1180" height="750" loading="lazy" alt="Actual UO:PvE launcher showing install, import, verify and PLAY controls"><figcaption>The Windows launcher · installation, updates and play in one place</figcaption></figure></section>`
  });

  await save(`${base}updates/`, {
    title: 'Updates & release notes', description: 'Follow UO:PvE gameplay fixes, client releases and player guides, with dated changes and verified downloads.', active: 'updates',
    content: `${breadcrumb('Updates')}<section class="page-heading wrap"><p class="eyebrow">FROM THE REALM</p><h1>The latest<br><em>UO:PvE updates.</em></h1><p class="lead">Gameplay changes, client releases and player guides, gathered in one place.</p></section><section class="section wrap"><div class="wiki-tools" role="search" aria-label="Search updates"><label for="update-search">Find an update<input id="update-search" type="search" maxlength="150" placeholder="Try combat, housing, maps or wiki…"></label></div><p id="update-results" role="status" aria-live="polite">${updates.length} updates</p><div class="update-list">${updates.map(update => `<article class="update-card" id="${update.id}" data-update-entry data-search="${esc([update.title, update.category, update.summary, ...update.changes].join(' '))}"><div class="update-meta"><time datetime="${esc(update.changedAt || update.date)}">${updateDateLabel(update)}</time><span class="tag">${esc(update.category)}</span></div><h2>${esc(update.title)}</h2><p>${esc(update.summary)}</p><ul>${update.changes.map(change => `<li>${esc(change)}</li>`).join('')}</ul><a class="text-link" href="${esc(update.link)}">${esc(update.linkLabel)} →</a></article>`).join('')}</div><p id="update-empty" class="callout" hidden>No updates match that search. Try a shorter term or clear the search.</p><noscript><p class="callout">The full update history is visible here. Enable JavaScript to search it.</p></noscript></section>`
  });
  return { articles: articles.length, updates: updates.length, pages: articles.length + 5 };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log('Built UO:PvE:', await buildUopve());
}
