import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { buildCatalogue } from './catalog.mjs';
import { validateGallery } from './validate-gallery.mjs';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
try {
  console.log('Validated gallery:', await validateGallery());
  const input = JSON.parse(await readFile(resolve(root, 'data/catalog.json'), 'utf8'));
  const output = buildCatalogue(input);
  await mkdir(resolve(root, 'public'), { recursive: true });
  // Write a classic script: the prepared site also opens from a local file without a server.
  const json = JSON.stringify(output, null, 2).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  await writeFile(resolve(root, 'public/catalog.js'), '// Generated by tools/build.mjs. Edit data/catalog.json instead.\nwindow.UO_CATALOG = ' + json + ';\n');
  const origins = output.site.assetBaseUrl ? ' ' + new URL(output.site.assetBaseUrl).origin : '';
  await writeFile(resolve(root, 'public/_headers'), `/*\n  X-Content-Type-Options: nosniff\n  X-Frame-Options: DENY\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'${origins}; media-src 'self'${origins}; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'none'\n\n/catalog.js\n  Cache-Control: public, max-age=0, must-revalidate\n\n/gallery/catalog.js\n  Cache-Control: public, max-age=0, must-revalidate\n\n/gallery/downloads/*\n  Content-Type: application/zip\n  Content-Disposition: attachment\n\n/gallery/catalog.js\n  Cache-Control: public, max-age=0, must-revalidate\n\n/gallery/catalog.js\n  Cache-Control: public, max-age=0, must-revalidate\n\n/gallery/downloads/*\n  Content-Type: application/zip\n  Content-Disposition: attachment\n\n/gallery/downloads/*\n  Content-Type: application/zip\n  Content-Disposition: attachment\n`);
  console.log(`Built catalogue: ${output.assets.length} published asset(s); ${input.assets.length - output.assets.length} draft(s) omitted.`);
} catch (error) {
  console.error('Build stopped: ' + error.message);
  process.exitCode = 1;
}
